networks:
  custom:
    ipam:
      config:
        - subnet: 10.9.0.0/16

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    networks:
      custom:

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=secret
    ports:
      - 8081:8081
    depends_on:
      - redis
    networks:
      custom:

  runwayfinance-api:
    image: ramirocaste/runwayfinance-api:latest
    build:
      context: .
      dockerfile: API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Redis=localhost
      - TiingoSettings__Url=https://api.tiingo.com
      - TiingoSettings__Token=17bfe3c07ce321045fa1d446b5cb79cf0f4cdaab
      - AlphaVantageSettings__Url=https://www.alphavantage.co
      - AlphaVantageSettings__ApiKey=HHOSHHKRN2N05NEE
      - VIRTUAL_PORT=80
    ports:
      - 7001:80
    depends_on:
      - redis
    networks:
      custom:

volumes:
  redis-data: